logging:
  level:
    root: ERROR
    tech.jhipster: INFO
    com.mycompany.myapp: INFO
    com.mycompany.myapp.config: INFO
    com.mycompany.myapp.web.websocket: WARN
    org.springframework.web.socket: WARN
    org.springframework.messaging: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql: WARN

spring:
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: false
  docker:
    compose:
      enabled: false
      skip:
        in-tests: false
      lifecycle-management: none
  jackson:
    serialization:
      indent-output: true

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:sqlserver://db38190.public.databaseasp.net:1433;databaseName=db38190;encrypt=false;trustServerCertificate=true;sendStringParametersAsUnicode=true;MultipleActiveResultSets=true
    username: db38190
    password: 'We8@b4%QS?j7'
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      poolName: Hikari
      auto-commit: false
      connection-timeout: 60000

    analytics:
      url: jdbc:sqlserver://db38190.public.databaseasp.net:1433;databaseName=db38190;encrypt=false;trustServerCertificate=true;sendStringParametersAsUnicode=true;MultipleActiveResultSets=true
      username: db38190
      password: 'We8@b4%QS?j7'
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      hikari:
        poolName: HikariAnalytics
        auto-commit: false
        maximum-pool-size: 5

  liquibase:
    contexts: dev, faker

  data:
    redis:
      host: redis-10289.crce178.ap-east-1-1.ec2.cloud.redislabs.com
      port: 10289
      password: 5ENdGvfn2FVLsTHyxbsYwlxWB8cwDZfE
      timeout: 2000ms
      ssl:
        enabled: false
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  cache:
    type: redis
    redis:
      time-to-live: 600000
      cache-null-values: false

  rabbitmq:
    host: moose.rmq.cloudamqp.com
    port: 5671
    username: qpmivqly
    password: kXWbjP-CBmxZtbRcwtOmDqaND8gjWT4D
    virtual-host: qpmivqly
    ssl:
      enabled: true
    listener:
      simple:
        acknowledge-mode: auto
        retry:
          enabled: true
          max-attempts: 3

  mail:
    host: ${SPRING_MAIL_HOST:smtp.gmail.com}
    port: ${SPRING_MAIL_PORT:587}
    username: catbamaytongdai@gmail.com
    password: ivte ulsr wcqw ydyu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: '*'
  messages:
    cache-duration: PT1S
  thymeleaf:
    cache: false

server:
  forward-headers-strategy: native
  servlet:
    async:
      request-timeout: 600000

jhipster:
  cors:
    allowed-origin-patterns: '*'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count,X-${jhipster.clientApp.name}-alert,X-${jhipster.clientApp.name}-error,X-${jhipster.clientApp.name}-params'
    allow-credentials: true
    max-age: 1800

  security:
    authentication:
      jwt:
        base64-secret: YzBjZjNjN2VjM2IwYzRlYzJhNWI1NTc2ZWFjZTlmMjE0OTNiYjcwZjFlMjZkMWY3ZDI5Nzg5ZWM5MmUyMTU2ZGIzMTNlNDg4MTJmNDg5YWM2MDFlMmVmYTFiYTVmYTFmYjU3MjIzNDU4OWRlZjExY2ZlNWM4Njg3NWMzZTNlZGU=
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000

  mail:
    base-url: http://127.0.0.1:8080
  logging:
    use-json-format: false
    logstash:
      enabled: false
      host: localhost
      port: 5000
      ring-buffer-size: 512

# CẤU HÌNH ZALOPAY (Sandbox)
zalopay:
  appid: '2553'
  key1: '9phuAOYhan4urywHTh0ndEXiM3pKHyv1'
  key2: 'kLtgPl8HHhfvMuDHPwKfgfsY4Ydm9eIz'
  endpoint: 'https://sb-openapi.zalopay.vn/v2/create'
  callback-url: 'http://localhost:8080/api/zalopay/callback'
  redirect-url: 'http://localhost:8080/payment-result'

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,configprops,threaddump,heapdump,prometheus
  endpoint:
    health:
      show-details: always
